### ISSUE TITLE
游戏下载失败，报403

### ISSUE THREAD

**Issue by alphonsetai** [rwv/chinese-dos-games#73]
Downloading 仙剑奇侠传 game file, url= https://***.***.***/static/gamedata/%E4%BB%99%E5%89%91%E5%A5%87%E4%BE%A0%E4%BC%A0.zip
Traceback (most recent call last):
  File "download_data.py", line 105, in <module>
    main()
  File "download_data.py", line 70, in main
    download(identifier, url, file)
  File "download_data.py", line 46, in download
    urllib.request.urlretrieve(url, file)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 248, in urlretriev
e
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 642, in http_respo
nse
    'http', request, response, code, msg, hdrs)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 504, in _call_chai
n
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 650, in http_error
_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by rwv** [comment]
下载脚本已经更新过，请使用最新的下载脚本下载。
